name: Issue Workflow
on:
  issues

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Created
        run: echo "Issue Created"
      - name: Event Details
        run: echo "Event Details ${{ toJson(github.event) }}"
      - name: Issue Title
        run: echo "Issue Title ${{ github.event.issue.title }}"
      - name: Issue Body
        run: echo "Issue Body ${{ github.event.issue.body }}"
      - name: Issue Number
        run: echo "Issue Number ${{ github.event.issue.number }}"